name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Get the current tag
        id: current_tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=TAG::$TAG"

      - name: Bump version and create tag
        id: tag_version
        run: |
          NEW_TAG=$(echo ${GITHUB_REF#refs/tags/} | awk -F. -v OFS=. '{$NF = $NF + 1 ; print}')
          echo "::set-output name=NEW_TAG::$NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.NEW_TAG }}
          release_name: Release ${{ steps.tag_version.outputs.NEW_TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/asset.zip
          asset_name: asset.zip
          asset_content_type: application/zip
